let selectedCatalog=null;let catalogs=[];
const total=document.getElementById("total"),discountText=document.getElementById("discountText"),quantityText=document.getElementById("quantityText");
function discountRate(q){return q>=5?.20:q===4?.15:q===3?.10:q===2?.05:0}
function updateTotal(){const q=document.getElementById("images").files.length;if(!selectedCatalog||!q){total.textContent=selectedCatalog?selectedCatalog.price+" €":"—";discountText.textContent="";quantityText.textContent=q?`${q} camiseta${q===1?'':'s'}`:"";return}const subtotal=q*selectedCatalog.price,rate=discountRate(q),discount=subtotal*rate;quantityText.textContent=`${q} camiseta${q===1?'':'s'} · Subtotal: ${subtotal.toFixed(2)} €`;discountText.textContent=rate?`Descuento por cantidad: ${(rate*100).toFixed(0)}% (-${discount.toFixed(2)} €)`:`Sin descuento por cantidad`;total.textContent=`${(subtotal-discount).toFixed(2)} €`}
function renderCatalogs(){const grid=document.getElementById("catalogGrid"),selector=document.getElementById("priceSelector");grid.innerHTML="";selector.innerHTML="";catalogs.forEach(c=>{grid.insertAdjacentHTML("beforeend",`<a class="catalog-card price20" href="${c.url}" target="_blank" rel="noopener"><div class="catalog-icon">👕</div><span>${escapeHtml(c.name)}</span><strong>${Number(c.price).toFixed(0)} €</strong><small>Ver camisetas <b>→</b></small></a>`);selector.insertAdjacentHTML("beforeend",`<button type="button" data-id="${escapeHtml(c.id)}">${escapeHtml(c.name)} · ${Number(c.price).toFixed(0)} €</button>`) });selector.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedCatalog=catalogs.find(c=>c.id===b.dataset.id);document.getElementById("catalogId").value=selectedCatalog.id;selector.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");updateTotal()})}
async function loadCatalogs(){const r=await fetch("/api/catalogs");catalogs=await r.json();renderCatalogs()};loadCatalogs();
const sizeOptions=()=>`<option value="">Selecciona talla *</option><optgroup label="Adulto">${["S","M","L","XL","XXL","XXXL"].map(s=>`<option value="${s}">${s}</option>`).join("")}</optgroup><optgroup label="Mujer">${["S","M","L","XL"].map(s=>`<option value="Mujer ${s}">Mujer ${s}</option>`).join("")}</optgroup><optgroup label="Niños">${["XXS=16","XS=18","S=20","M=22","L=24","XL=26","XXL=28"].map(s=>`<option value="Niños ${s}">Niños ${s}</option>`).join("")}</optgroup>`;
document.getElementById("images").addEventListener("change",e=>{const p=document.getElementById("preview");p.innerHTML="";[...e.target.files].forEach((f,i)=>{const card=document.createElement("div");card.className="preview-item";const img=document.createElement("img");img.src=URL.createObjectURL(f);const label=document.createElement("label");label.className="size-select-label";label.innerHTML=`Talla <select class="size-select" data-index="${i}" required>${sizeOptions()}</select>`;card.appendChild(img);card.appendChild(label);p.appendChild(card)});updateTotal()});
document.getElementById("orderForm").addEventListener("submit",async e=>{e.preventDefault();const msg=document.getElementById("message");if(!selectedCatalog){msg.textContent="Selecciona un catálogo.";return}const files=[...document.getElementById("images").files];const sizes=[...document.querySelectorAll(".size-select")].map(s=>s.value);if(!files.length){msg.textContent="Sube al menos una captura.";return}if(sizes.length!==files.length||sizes.some(s=>!s)){msg.textContent="Debes elegir una talla para cada camiseta.";return}const fd=new FormData(e.target);fd.set("sizes",JSON.stringify(sizes));const res=await fetch("/api/orders",{method:"POST",body:fd});const data=await res.json();if(!res.ok){msg.textContent=data.error||"Error";return}msg.textContent=`Pedido #${data.id} enviado correctamente. Total: ${Number(data.total).toFixed(2)} €. Descuento: ${Number(data.discountRate*100).toFixed(0)}%.`;e.target.reset();document.getElementById("preview").innerHTML="";selectedCatalog=null;document.getElementById("catalogId").value="";total.textContent="—";discountText.textContent="";quantityText.textContent="";document.querySelectorAll("#priceSelector button").forEach(x=>x.classList.remove("active"))});
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}