let selectedCatalog=null;let catalogs=[];
const total=document.getElementById("total"),discountText=document.getElementById("discountText"),quantityText=document.getElementById("quantityText");
function discountRate(q){return q>=5?.20:q===4?.15:q===3?.10:q===2?.05:0}
function getCartItems(){return [...document.querySelectorAll(".preview-item")].map((card,i)=>({index:i,size:card.querySelector(".size-select")?.value||"",quantity:Math.max(1,Number(card.querySelector(".qty-input")?.value||1))}));}
function updateTotal(){const items=getCartItems();const q=items.reduce((n,x)=>n+x.quantity,0);if(!selectedCatalog||!q){total.textContent=selectedCatalog?Number(selectedCatalog.price).toFixed(2)+" €":"—";discountText.textContent="";quantityText.textContent=q?`${q} camiseta${q===1?'':'s'}`:"";return}const subtotal=q*Number(selectedCatalog.price),rate=discountRate(q),discount=subtotal*rate;quantityText.textContent=`${q} camiseta${q===1?'':'s'} · Subtotal: ${subtotal.toFixed(2)} €`;discountText.textContent=rate?`Descuento por cantidad: ${(rate*100).toFixed(0)}% (-${discount.toFixed(2)} €)`:`Sin descuento por cantidad`;total.textContent=`${(subtotal-discount).toFixed(2)} €`}
function renderCatalogs(){const grid=document.getElementById("catalogGrid"),selector=document.getElementById("priceSelector");grid.innerHTML="";selector.innerHTML="";catalogs.forEach(c=>{grid.insertAdjacentHTML("beforeend",`<a class="catalog-card price20" href="${escapeHtml(c.url)}" target="_blank" rel="noopener"><div class="catalog-icon">👕</div><span>${escapeHtml(c.name)}</span><strong>${Number(c.price).toFixed(0)} €</strong><small>Ver camisetas <b>→</b></small></a>`);selector.insertAdjacentHTML("beforeend",`<button type="button" data-id="${escapeHtml(c.id)}">${escapeHtml(c.name)} · ${Number(c.price).toFixed(0)} €</button>`) });selector.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedCatalog=catalogs.find(c=>c.id===b.dataset.id);document.getElementById("catalogId").value=selectedCatalog.id;selector.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");updateTotal()})}
async function loadCatalogs(){const r=await fetch("/api/catalogs");catalogs=await r.json();renderCatalogs()};loadCatalogs();
const sizeOptions=()=>`<option value="">Selecciona talla *</option><optgroup label="Adulto">${["S","M","L","XL","XXL","XXXL"].map(s=>`<option value="${s}">${s}</option>`).join("")}</optgroup><optgroup label="Mujer">${["S","M","L","XL"].map(s=>`<option value="Mujer ${s}">Mujer ${s}</option>`).join("")}</optgroup><optgroup label="Niños">${["XXS=16","XS=18","S=20","M=22","L=24","XL=26","XXL=28"].map(s=>`<option value="Niños ${s}">Niños ${s}</option>`).join("")}</optgroup>`;
document.getElementById("images").addEventListener("change",e=>{const p=document.getElementById("preview");p.innerHTML="";[...e.target.files].forEach((f,i)=>{const card=document.createElement("div");card.className="preview-item";const img=document.createElement("img");img.src=URL.createObjectURL(f);const label=document.createElement("label");label.className="size-select-label";label.innerHTML=`Talla <select class="size-select" data-index="${i}" required>${sizeOptions()}</select>`;const qty=document.createElement("div");qty.className="qty-control";qty.innerHTML=`<button type="button" class="qty-minus" aria-label="Restar">−</button><input class="qty-input" type="number" min="1" max="99" value="1" aria-label="Cantidad"><button type="button" class="qty-plus" aria-label="Sumar">+</button>`;qty.querySelector(".qty-minus").onclick=()=>{const x=qty.querySelector(".qty-input");x.value=Math.max(1,Number(x.value||1)-1);updateTotal()};qty.querySelector(".qty-plus").onclick=()=>{const x=qty.querySelector(".qty-input");x.value=Math.min(99,Number(x.value||1)+1);updateTotal()};qty.querySelector(".qty-input").oninput=updateTotal;card.appendChild(img);card.appendChild(label);card.appendChild(qty);p.appendChild(card)});updateTotal()});
document.getElementById("orderForm").addEventListener("submit",async e=>{e.preventDefault();const msg=document.getElementById("message");if(!selectedCatalog){msg.textContent="Selecciona un catálogo.";return}const files=[...document.getElementById("images").files];const items=getCartItems();if(!files.length){msg.textContent="Sube al menos una captura.";return}if(items.length!==files.length||items.some(x=>!x.size)){msg.textContent="Debes elegir una talla para cada camiseta.";return}const fd=new FormData(e.target);fd.set("items",JSON.stringify(items));const res=await fetch("/api/orders",{method:"POST",body:fd});const data=await res.json();if(!res.ok){msg.textContent=data.error||"Error";return}msg.textContent=`Pedido #${data.id} enviado correctamente. Total: ${Number(data.total).toFixed(2)} €. Descuento: ${Number(data.discount||0).toFixed(2)} €.`;e.target.reset();document.getElementById("preview").innerHTML="";selectedCatalog=null;document.getElementById("catalogId").value="";total.textContent="—";discountText.textContent="";quantityText.textContent="";document.querySelectorAll("#priceSelector button").forEach(x=>x.classList.remove("active"))});
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
